[0m19:09:16.034963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35fa002050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35f826a140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35f826a050>]}


============================== 19:09:16.045516 | d1bf291d-34c6-4850-a64c-e915eb2f38c8 ==============================
[0m19:09:16.045516 [info ] [MainThread]: Running with dbt=1.7.5
[0m19:09:16.046099 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/usr/app', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m19:09:16.046647 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:09:16.047958 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.08642221, "process_user_time": 2.33941, "process_kernel_time": 0.129967, "process_mem_max_rss": "88784", "process_in_blocks": "648", "process_out_blocks": "48", "command_success": false}
[0m19:09:16.048528 [debug] [MainThread]: Command `dbt run` failed at 19:09:16.048388 after 0.09 seconds
[0m19:09:16.048925 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35fa002050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35fc286c20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f35f82c0220>]}
[0m19:09:16.049349 [debug] [MainThread]: Flushing usage events
[0m19:11:44.744204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f292888e5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2926afa020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2926af9fc0>]}


============================== 19:11:44.747706 | 86f4259b-fb8c-4baf-80bf-249b2cc508f0 ==============================
[0m19:11:44.747706 [info ] [MainThread]: Running with dbt=1.7.5
[0m19:11:44.748338 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/usr/app', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:11:44.748815 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:11:44.750062 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.064025685, "process_user_time": 2.457659, "process_kernel_time": 0.21979, "process_mem_max_rss": "87556", "process_in_blocks": "64096", "process_out_blocks": "8", "command_success": false}
[0m19:11:44.750638 [debug] [MainThread]: Command `dbt run` failed at 19:11:44.750497 after 0.06 seconds
[0m19:11:44.751031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f292888e5c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2926afa0b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f2926af9fc0>]}
[0m19:11:44.751439 [debug] [MainThread]: Flushing usage events
[0m19:14:15.813778 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a4052650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a2282050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a2281ff0>]}


============================== 19:14:15.817908 | 14f07af1-71e5-4715-a740-0b750e9b8b0b ==============================
[0m19:14:15.817908 [info ] [MainThread]: Running with dbt=1.7.5
[0m19:14:15.818583 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/usr/app', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:14:15.819085 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:14:15.820496 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.06722211, "process_user_time": 2.388822, "process_kernel_time": 0.238882, "process_mem_max_rss": "87648", "process_in_blocks": "65040", "process_out_blocks": "8", "command_success": false}
[0m19:14:15.821064 [debug] [MainThread]: Command `dbt run` failed at 19:14:15.820919 after 0.07 seconds
[0m19:14:15.821443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a4052650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a22820e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f60a2281ff0>]}
[0m19:14:15.821871 [debug] [MainThread]: Flushing usage events
[0m19:15:21.400069 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c4ea6290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c3116110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c31160b0>]}


============================== 19:15:21.403636 | af3219af-906d-492e-8b77-d0e295a21254 ==============================
[0m19:15:21.403636 [info ] [MainThread]: Running with dbt=1.7.5
[0m19:15:21.404234 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/usr/app', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:15:21.404766 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:15:21.406186 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.063327834, "process_user_time": 2.382206, "process_kernel_time": 0.159478, "process_mem_max_rss": "87716", "process_in_blocks": "63424", "process_out_blocks": "16", "command_success": false}
[0m19:15:21.406768 [debug] [MainThread]: Command `dbt run` failed at 19:15:21.406623 after 0.06 seconds
[0m19:15:21.407164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c4ea6290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c31161a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff2c31160b0>]}
[0m19:15:21.407588 [debug] [MainThread]: Flushing usage events
[0m20:20:44.777014 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564d8db730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564bbca950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564bbcb9a0>]}


============================== 20:20:44.783622 | 5a0cf81c-4ea8-4e16-b0ab-3a9053a5e4d5 ==============================
[0m20:20:44.783622 [info ] [MainThread]: Running with dbt=1.7.5
[0m20:20:44.784230 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/usr/app', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m20:20:44.784711 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:20:44.785571 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.063882224, "process_user_time": 2.39389, "process_kernel_time": 0.150244, "process_mem_max_rss": "88996", "process_in_blocks": "24", "process_out_blocks": "616", "command_success": false}
[0m20:20:44.786184 [debug] [MainThread]: Command `dbt run` failed at 20:20:44.786042 after 0.06 seconds
[0m20:20:44.786593 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564d8db730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564fb27640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f564bbcbdc0>]}
[0m20:20:44.787017 [debug] [MainThread]: Flushing usage events
[0m20:22:14.395353 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d5075a050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d4eb00b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d4eb00bb0>]}


============================== 20:22:14.398267 | acb59295-1bdb-41a0-a715-dab8b60084af ==============================
[0m20:22:14.398267 [info ] [MainThread]: Running with dbt=1.7.5
[0m20:22:14.398864 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/usr/app/bw_project/', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir /usr/app/bw_project/', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m20:22:14.399469 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:22:14.400359 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.007125391, "process_user_time": 2.339253, "process_kernel_time": 0.079974, "process_mem_max_rss": "86700", "process_out_blocks": "16", "command_success": false, "process_in_blocks": "0"}
[0m20:22:14.400931 [debug] [MainThread]: Command `dbt run` failed at 20:22:14.400789 after 0.01 seconds
[0m20:22:14.401339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d5075a050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d529dace0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f3d4eb001c0>]}
[0m20:22:14.401768 [debug] [MainThread]: Flushing usage events
[0m20:22:44.183046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f54981d2740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f54964021a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5496402140>]}


============================== 20:22:44.185850 | 78307c0c-a99d-4f78-8f6b-8e9b50f12386 ==============================
[0m20:22:44.185850 [info ] [MainThread]: Running with dbt=1.7.5
[0m20:22:44.186437 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/usr/app/', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /usr/app/', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:22:44.186932 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /usr/app/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:22:44.187771 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.05944517, "process_user_time": 2.393967, "process_kernel_time": 0.069824, "process_mem_max_rss": "87912", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m20:22:44.188341 [debug] [MainThread]: Command `dbt run` failed at 20:22:44.188196 after 0.06 seconds
[0m20:22:44.188737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f54981d2740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5496402230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5496402140>]}
[0m20:22:44.189169 [debug] [MainThread]: Flushing usage events
